// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/v1.0/[deviceId]/command.ts";
import * as $1 from "./routes/api/v1.0/[deviceId]/status.ts";

const manifest = {
  routes: {
    "./routes/api/v1.0/[deviceId]/command.ts": $0,
    "./routes/api/v1.0/[deviceId]/status.ts": $1,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
